baseURL = 'https://lulushenanigans.me'
languageCode = 'fr-fr'
title = "Lulu's Shenanigans"
theme = 'Themanigans'
DefaultContentLanguage = 'fr'
[params]
    name = 'Lucien Astié'
    job = 'Engineer student'
    linkedin = 'https://www.linkedin.com/in/lucien-astie'
    github = 'https://www.github.com/lucienastie'
    mail = 'lucien.astie@gmail.com'
[permalinks]
    posts=":section/:title"

[languages]
  [languages.fr]
    weight=1
  [languages.en]
    weight=2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true