name = "Themanigans"
license = "MIT"
description = ""
homepage = "https://lulushenanigans.me"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Globuzma"
  homepage = "https://www.lulushenanigans.me"
